version: '1.2.{build}.0'
image: Visual Studio 2019

configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  nuget restore SevenZip.sln

environment:
  COVERALLS_REPO_TOKEN:  
    secure: uhHSJvf0G4qxIzWt2740yqjI1a5jGRM0bUFdf3nWGUYrHBc0rJXHn0wExDiWMz/O

build:
  parallel: true
  project: 'SevenZip.sln'
  publish_nuget: false

after_build:
  - cmd: nuget pack package.nuspec -version "%APPVEYOR_BUILD_VERSION%"

after_test:
  - ps: Invoke-Expression ($env:USERPROFILE + '\.nuget\packages\OpenCover\4.7.922\tools\OpenCover.Console.exe -register:user -filter:"+[*]* -[SevenZip.Tests]* -[nunit.framework]*" -target:"' + $env:USERPROFILE + '\.nuget\packages\nunit.consolerunner\3.10.0\tools\nunit3-console.exe" -targetargs:"/domain:single Stage/Release/net45/SevenZip.Tests.dll" -output:coverage.xml')
  - ps: Invoke-Expression ($env:USERPROFILE + '\.nuget\packages\coveralls.io.\1.4.2\tools\coveralls.net.exe --debug --opencover "coverage.xml" -r %COVERALLS_REPO_TOKEN%')

artifacts:
  - path: 'Squid-Box.SevenZip*.nupkg'
  - path: 'coverage.xml'

deploy:
  provider: NuGet
  api_key:
    secure: AWbl6aAa09NxVWFo9EDRC12RhY090havc8aWB9j0S4crFvICIkIvON0gUxG2q8QZ
  artifact: /SevenZip.*\.nupkg/
  skip_symbols: false
  on:
    branch: master
